version: "3.8"

services:
  product-app:
    image: hsvg/product-app:latest
    container_name: product-app
    build:
      context: ./product-app
      args:
        - APP_NAME=product-app
        - APP_VERSION=0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
    expose:
      - 8081
    ports:
      - 8081:8081
